name: Build containers from conda environments

on:
  pull_request:
    paths:
      - 'container/containers.csv'

jobs:
  update_csv:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: containers
          create-args: numpy pandas pyyaml
          generate-run-shell: true

      - name: Regenerate environment YAML files
        shell: micromamba-shell {0}
        run: python3 .github/workflows/export_envs.py

      - name: Commit changes to YAML files
        uses: EndBug/add-and-commit@v9
        with:
          push: true

      - name: Call container_build
        uses: .github/workflows/container_build.yml 
        with:
          commit_sha: ${{ github.event.pull_request.head.sha }}

